- include_tasks: teardown.yml
  when: teardown

- name: provision workshop in AWS public cloud
  block:
    - name: provision aws resources and instances
      include_tasks: provision.yml

    - name: create instructor_inventory, and student files
      include_tasks: create_inventory.yml
  when: not teardown

- name: CONFIGURE ROUTERS FOR SPECIAL
  include_tasks: configure_routers.yml
  when: special is defined
